name: Daily Stock Analysis

# 每日北京时间14:50运行 (UTC时间06:50)
on:
  schedule:
    - cron: '45 6 * * *'  # UTC时间，对应北京时间14:45
  workflow_dispatch:  # 允许手动触发

jobs:
  stock-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run stock analysis
      run: |
        python main.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push changes
      run: |
        git add .
        git diff --staged --quiet || git commit -m "Daily stock analysis update - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}